### ISSUE TITLE
Update character sheet for Game Patch 1.1.3 

### ISSUE THREAD

**Issue by emcezet** [Project-Tempestus/tempestus_character_sheet#35]
Game mechanics patch:
* Base marksmanship 10% -> 15%
* Vostroya Regiment Bonuses:
  * Constitution:15% ->10%;
  * Health Points: 20 HP -> 30 HP
  * Strength: 0% -> 10%

**Comment by theShaddy** [comment]
Marksman:

- Marksmanship 10% -> 5%
