### ISSUE TITLE
Add field for selected colors

### ISSUE THREAD

**Issue by emcezet** [Project-Tempestus/tempestus_character_sheet#7]
Field:
- hair color (text field)
- clothing colorstyle (options?)
- skin color (text field or select?)

**Comment by theShaddy** [comment]
Clothing options problematic. Dependent on different factors. E.g. chirurgeon always has one other color scheme available which would be dark-green. No specific options would be better imo.

**Comment by emcezet** [comment]
will be done as text inputs
